# Generated by Django 4.2.1 on 2023-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_remove_application_status_application_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp135', max_length=70),
        ),
    ]
