# Generated by Django 4.2.1 on 2023-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_alter_application_cv_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp985', max_length=70),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
