# Generated by Django 4.2.2 on 2023-06-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_alter_employee_emp_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp838', max_length=70),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
