# Generated by Django 4.2.2 on 2023-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_employee_username_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp103', max_length=70),
        ),
    ]
